language: python

services:
  - redis-server

python:
    - "2.7"

install:
    - pip install -r requirements.txt --use-mirrors
    - pip install python-coveralls --use-mirrors
    - python setup.py -q install

script:
    - py.test tests/ --cov django_flanker --cov-report term-missing

after_success:
    - coveralls
