language: python

services:
  - redis-server

python:
    - "2.7"

install:
    - pip install -q -r requirements.txt --use-mirrors
    - pip install -q coveralls --use-mirrors
    - python setup.py -q install

script: py.test tests/ --cov django_flanker --cov-report term --cov-report xml

after_success:
    coveralls
