language: python
python:
    - "2.6"
    - "2.7"

env:
    - DJANGO_VERSION=1.4.5
    - DJANGO_VERSION=1.5.5
    - DJANGO_VERSION=1.6.1

install:
    - pip install -q django==$DJANGO_VERSION
    - pip install -r requirements.txt
    - python setup.py -q install

script: py.test tests/ --cov django_flanker
